/*
 * Copyright (c) 2010-2018. Axon Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.axonframework.extensions.reactor.eventstore.factories;


/**
 * Jdbc table factory for HSQL databases.
 *
 * @author Rene de Waele
 * @since 3.0
 */
public class H2EventTableFactory extends AbstractEventTableFactory {

    /**
     * Singleton H2EventTableFactory instance
     */
    public static final H2EventTableFactory INSTANCE = new H2EventTableFactory();

    /**
     * Default constructor of the factory
     */
    protected H2EventTableFactory() {
    }

    @Override
    protected String idColumnType() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0)";
    }

    @Override
    protected String payloadType() {
        return "bytea";
    }
}
