dist: bionic
language: java
sudo: required
services:
- docker
jobs:
  include:
  - name: JDK 8
    jdk: openjdk8
    env: MVN_BUILD_SCRIPT="clean verify"
  - name: JDK 11 with Sonar analysis
    jdk: openjdk11
    env: MVN_BUILD_SCRIPT="-Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-reactor"
install: true
cache:
  directories:
  - "$HOME/.m2"
script:
  - mvn -version
  - mvn -B -U $MVN_BUILD_SCRIPT

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "Byhy5L5cGZ7dlymrXg6/5SRSmCSbBLq2DbmBDHnWKTq2TfbhCgNvkrjI7R4i4xwkvIcNEuFblULUzGSz7+lGcTxpNsMt9MZKxnH8Hj+PAWNOLdHQGty9+EXyQCF9q4x+td/Sqp/EuCFBYvDyVCVCIVbyMKe6bD9J6hfC8QWpK1Q3eDOVGI9N9AtawkDVxoRYH2Br4tkxrSAQcNA8w53oqycNPotDeIQS0K/780AULXzb7i8fYO/Uz4x+pnh348O35009WTS2eUU8yjoZ4UJmBJ1ocN3Xtj7NyllPPr9e5QZfPi+xAz2YecWLSrwpyPiS4nPmzAyPcYtohYc/HiSntZvP9mZYmCVPb4GbZAIPrgXSjtPX2RMd9FVwLH2PJ2VX4uxQ2B9maCuETj7zV8CW6zCUNJJMRtpHzIvNY/Nj+9H8n0EKepMKFxU0uWq34JJcWTvLX/fITGs6KljNivMq/w3Hue/akW2b9XoqLzfryTUYIFShZWp/rhQdset67ReBvtLFE+lTH+XoNkvd+psV37j51nmnnFUNEfITpvIi+3zStytCK213coyNU2cKCaa93Jfvgt90OJBNBf9M1RpP+oyQ++kSWkUFY8u/QMW1walR8sFlKmkw6NRaupgEc/QpbkGzSdcT5laiDrhxisNsaRCTuF42QmlT9nQhP0ZG+EQ="
