# We want to run this on Ubuntu 18.04 LTS
dist: bionic

language: java

sudo: required

services:
  - docker

jobs:
  include:
    - name: "JDK 8"
      jdk: openjdk8
      env: MVN_BUILD_SCRIPT="clean verify"
    - name: "JDK 11 with Sonar analysis"
      jdk: openjdk11
      env: MVN_BUILD_SCRIPT="-Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-reactor"

install: true

cache:
  directories:
    - $HOME/.m2

# We switch JDK by setting the JAVA_HOME environment variable. All JDKs are under the same base directory.
script:
  - mvn -version
  - mvn -B -U $MVN_BUILD_SCRIPT

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "fitFKCrBc/mDBOQyU2AMOXpD+/yNlZMi3qWHGscX5pq8e29tnVZrfaSxggoe+s1wU7eCJ67patxipevhx9ZGlpgPVbwP9ztX+5bngoRFpWePt3d7fUZbU2yRJ0lQYA5L4NlnB88M7nJ2+VCfBCkgL3j+freuoRzFHozze7IoX7i3RqooBovhUFUrlY/fyHEmFcsLv8oyUY1dpf/A84a+gH4fC2CSdAryOS71ZUxVdFSInFodziBvcjrHNwPejFlnAr+5wmUfrtKjDmMWiSoLxKyv5k9UdTkMKhLDxnxRf1WLm5H8fHrrJ+aApC1G8ROprMsfexEq8/A6vHJiKcQ9kR2374C0oH8ZzQaFNGopc0vHDzsrxPLGKTH0kh5KylmGnN3QxmZOI9v29si/wEDfLpuOZv9qXvT/1tnzlu3GACbrrKlxvuaBpTRaqnispjXqjH8umGSrksV1bJxbB8VY+zRnMUEGxSFdaFTHevevqrYfbMRPWBXsQaTHbEg/0PJR8wZm2Ns8AYf0qVqKaAfZoUU+FoyA5gPZo8UUvh+EU6yp5lYoXUkzEmlIkmwrdqxMnuBqjkmJp8tNRXBHtNyTe52YnvdjI9y9Gk9LCKMI4EyOAcQuh9BaOZNbXxo50gfMl8iFpEYlWjBgmA8gKRVOJz50dQjuvApXUpyoiGMfnv4="
