dist: bionic
language: java
sudo: required
services:
- docker
jobs:
  include:
  - name: JDK 8
    jdk: openjdk8
    env: MVN_BUILD_SCRIPT="clean verify"
  - name: JDK 11 with Sonar analysis
    jdk: openjdk11
    env: MVN_BUILD_SCRIPT="-Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-reactor"
install: true
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn -version
- mvn -B -U $MVN_BUILD_SCRIPT
notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "AxonFramework"
    token:
      secure: MfUupa8OpTs/ioSyk7z6DoacZ126ZfxNMGVvM3VdKTsLVoGSkycF1hMrO93CkNbMZ3PA9H133NOabsfZUMsi/09lP9Dl7pdE4wnLZ/cLR7aZCgHGDYhD246ZZGa23bzQ03WP+tleWQeNDKyT7ftToz9A/Y2h9Du1auDzQoLzmyaJxq7530NcZmbw/grPp/5DNOsEbtZ/zZr7ssgEV5TP9fLQRAw0I9EXzrapY1hIzURaRzGX6QVN23aVQP+ufIjJvXXbbmjuefY4ga0Kza3AXBqC9sr2rTrHB1QSiP+o/c0e/ji2bNmnPQ8P+AK/r0/Ys9EkOpocgPAY8vH0f78DDU/befmpHoMomu13T9PKktraixby9DmVRizX55LqVgVeN5MJPhpgxYCQr0VNiOMbo6dAwbbXV5pfEe4R16TqWHfS4Iy/BEj8UmfIVdsAuD8XUrUzLhULsllaLFdGHXWBcVIRCiUoY671chA44a3XNU2BDBtRPw8dTr3NPmXDkALYoCq22P4rdW9k4rmLW+Tpcx4GRl5SLjrL/yL3Ax4fkeRrqE3aUWCd8H2X2UMjMVGYlteWkqNMNwQYmKhWSHAYk3xuqS45vly0/DzxGARIN2/pILRcYXaa83S2yBv3oLF/lL2eDdume2D0kOUqGUAuGBwryle8zFQYPDLegokMXdU=
#      secure: JD6zhqgYM3VK06JRRQmd3CwHJoJ3d33/AvYhNlLkvlpDye8Bmr7r8W0kMWr+Sch5FPTvq7ihO7UybAuH6OTrS9LvhqBZnY85s0C1WKEdTggOARETGhvMBfoNqu94vzi1J9usa11u/xuTzR8rLpscm77TQ+0DMj+sD0VzxNQI26wG1RZRqhUl6SOXeKwEccR5iNuLYKVrk7HAr3OVSiy0Xn6/6inHpkdgLBYCFFLp++7fZNzXQjGOtAc9GDmMmNaaQfQaDhX2inNe73X6axE+yzBxfD42WWIWYJmYNsXQciNtE1ODMf75w4JW8+YUY47UPZdIFbV0tQxgBQx8o8KgIz4bBrTUcd5cBNq//SBoE0tAXgjWXzhvIcpS43HS8tyUkXj2caTX+awUyOmr2m+5ENu3wiCLYidI9KSiqulhMVNPzaNM5EoCNqGZxqhZJD22lqQl0eBlR+VnWI7STpkBs1oBoPTyhjex/9m2Pv6yWjjDSn/gSBxnkGDUfSZ74YFrXMRVGQemiMbVyZ9G6QqqbbZrVmdlFj0Jmfrz+YXXnwLYlxV6dn6rpMMQAtM1ASnSNdLVitQdcozEOS8FmULifhG4XvLWSabuV24DzIfcT6PLqNmVnPfhTSf5giQdB1BsmyzR2rKQlGrNLyN1kHU4yN9iK7e1+dzsvK77L1lszOU=
